'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.239
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("db_fixer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  37DC8144 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property crc() As String
            Get
                Return ResourceManager.GetString("crc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  ULJS-00001 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property gid() As String
            Get
                Return ResourceManager.GetString("gid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  name &quot;s1&quot;
        '''description &quot;s2&quot;
        '''serial &quot;s3&quot;
        '''rom( name &quot;s4.iso&quot; size s5 crc s6 ) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property preview() As String
            Get
                Return ResourceManager.GetString("preview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  906297344 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property size() As String
            Get
                Return ResourceManager.GetString("size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  リッジレーサー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property title() As String
            Get
                Return ResourceManager.GetString("title", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
