copy MKIJIRO.prx MKIJIRO\MKIJIRO.prx
copy MKIJIRO_POPS.prx MKIJIRO\MKIJIRO_POPS.prx
copy MKIJIRO620.prx MKIJIRO635.prx
copy MKIJIRO_POPS.prx MKIJIRO620POPS.prx
copy MKIJIRO_POPS.prx MKIJIRO635POPS.prx
copy MKIJIRO620.prx MKIJIRO\MKIJIRO620.prx
copy MKIJIRO635.prx MKIJIRO\MKIJIRO635.prx
copy MKIJIRO620POPS.prx MKIJIRO\MKIJIRO620POPS.prx
copy MKIJIRO635POPS.prx MKIJIRO\MKIJIRO635POPS.prx
del *.elf
del objects\*.o
move MKIJIRO_POPS.prx g:\seplugins\MKIJIRO_POPS.prx
move MKIJIRO.prx f:\seplugins\MKIJIRO.prx
move MKIJIROHEN620.prx f:\seplugins\HEN620TA\MKIJIRO.prx
move MKIJIROHEN635.prx g:\plugins\MKIJIRO.prx
del *.prx