//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.269
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFPUHELP.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VFPUHELP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   □□□□□□□□□□□■■■□□■■■■■■■■■■■■□□
        ///□□□□□□□□□□■■□■■□□■■■■■■■■■■■■□
        ///□□□□□□□□□■■■■□■■■■□□■■■■■■■■■□
        ///□□□□□□□□□■■■■■■■□□□□□■■□□■■■■■
        ///□□□□□□□□■■■■■□□□□□□□□□□□□□□■■■
        ///□□□□□□□□■■■■■□□□□□□□□□□□□□□□■■
        ///□□□□□□□□■■■■■□□□□□□□□□□□□□□□■■
        ///□□□□□□□□■■■■■□□□□□□□□□□□□□□□■■
        ///□□□□□□□□■■■■■□□□□□□□□□□□□□□□■■
        ///□□□□□□□□■■■■■□□□□□□□□□□□□□□□■■
        ///□□□□□□□□■■■■□□□□□□□□□□□□□□□□■□
        ///□□□□□□□■■■■■□□■■■■□□□□□□□□□□■□
        ///□□□□□□□■□■■□■■■■■■■■□□□□■■■■■□
        ///□□□□□□□■□□■□■■■■■■■■■□■■■■■■■□
        ///□□□□□□□■□■■□□■■■■■■■□□■■■■■■■□
        ///□□□□□□□■□□■□□□■■■■■■□□□■■■■■■□
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   , ---　､_
        ///    　　　　　　　 　 ／ミミミヾヾヽ､＿
        ///    　　　　　　　∠ヾヾヾヾヾヾjj┴彡ﾆヽ
        ///    　　　　　　/ ,　-ー‐&apos;&quot;´´´　　　 ヾ.三ヽ
        ///    　　　　　 ,&apos; /　　　　　　　　　　　　ヾ三ヽ
        ///    　　　　　 j |　　　　　　　　　　　　 / }ミ　i
        ///    　　　　　 | |　　　　　　　 　 　 　 / /ミ　 !
        ///    　　　　　 } | r､　　　　　　　　　　l　ﾞiミ __」
        ///    　　　　　　|]ﾑヽ､_　　　　__∠二､__,ｨ|/ ｨ }
        ///    　　　　　　| 　 ￣｀ﾐｌ==r&apos;´　　 　 /　|lぅ　lj　　
        ///    　　　　　　「!ヽ､_____j　ヽ､＿　 -&apos;　　ﾚ&apos;r&apos;/
        ///    　　　　　　 `! 　 　 j　　ヽ　 　 　 　 j_ノ
        ///    　　　　　　　&apos;,　 　 ヽｧ_ &apos;┘　　　　　,i
        ///    　　　　　　　 ヽ　　___&apos;...＿_　　 i 　 ﾊ
        ///    　　　　　　　　 ヽ　ﾞ二二　`　 ,&apos; ／　λ
        ///    　　　　　　　　　入　 　 　 　 ／　 ／　|ヽ
        ///    　 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   , ---　､_　　　 , ---　､_　 , ---　､_　　 -　､_ 　　-　､_　-　､_-　､_-　､__､_
        ///    　　　 　 ／ミミミヾヾヽ､＿ ミミミヾヾヽ､＿ ミヾヾヽ､＿ ヾヽ､＿ ヾヽ､＿　ヽ､＿ヽ､＿､＿＿
        ///    　　　∠ヾヾヾヾヾヾjj┴彡ﾆヾヾヾヾjj┴彡ﾆヾヾjj┴彡ﾆヽj┴彡ﾆヽ┴彡ﾆヽ彡ﾆヽ...ﾆヽ.ﾆヽヽヽ
        ///    　　/ ,　-ー‐&apos;&quot;´´´　　　 ヾ.三ヽ‐&apos;&quot;´　　 ヾ.三ヽ　　 ヾ.三ヽ　 ヾ.三ヽ　ヾ.三ヽヾ.三ヽ.三ヽ三ヽヽヽ
        ///    　 ,&apos; /　　　　　　　　　　　　ヾ三ヽ　　　　　ヾ三ヽ　　　ヾ三ヽ　　ヾ三ヽ　ヾ三ヽヾ三ヽ..三ヽ三ヽヽヽ
        ///    　 j |　　　　　　　　　　　　 / }ミ　i　　　　　./ }ミ　i　　.../ }ミ　i　.../ }ミ　i.../ }ミ　i　}ミ　i..ミ　i　　iiiii
        ///    　 | |　　　　　　　 　 　 　 / /ミ　 !　 　 　 / /ミ　 ! 　 / /ミ　 !　/ /ミ　 !/ /ミ　 !/ミ　 !.ミ　 !　.. !!!!!
        ///    　 } | r､　　　　　　　　　　l　ﾞi [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _二__　　 ＿_
        ///　　　　　　　　　　　　 　　　　　,-‐ｰ&apos;&apos;&quot;´､:::::::,-&apos;&quot;´:::::::::｀‐､
        ///　　　　　 　　　　　　　　 　　 /::-‐ｰ､:::::ヽ/:::::::::::::::::::::::::::ヽ
        ///　　　　　　　　　　　　　　　 &gt;&apos;´:::::::::::::::＼:/⌒｀`‐:::::::::::::::::::::&apos;,
        ///　　　　　　　　　　　　　　 /:::::::::::::ヽ::::::::ﾐ,-&apos;&apos;&quot;´｀` ‐､:::::::::::::::::&apos;,
        ///　　　　　　　　　　　　　　/:::::::::::::::::::ヽヽ::i::::,-&apos;&apos;&quot;´ヽ:::ヽ:::::ミ::::::l
        ///　　　　　　　　　　　　　　l::::::::,-‐ｰ-､::::::,-‐ｰ､;;;;;;;;ﾐ&apos;,:::::ヽ:三≡l
        ///　　　　　　　　　　　　　　l::::/　　　　 ｀&apos;　　　　　　　:l::::::l::::::::::::l
        ///　　　　　　　　　　　　　　l::l　　　　　　　　　　　　　　l::ﾉ:::::::::,-､
        ///　　　　　　　　　 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /:::/::/::::/::::ミ/:::::::::::::::::/:::::::::::::::::::ヽヽ::i::::,-&apos;&apos;&quot;´ヽ:::ヽ:::::ミ::::::l/;;;;;:::::::::::::::::::::::::::::::::::::::::::::::&apos;,
        ///    ./::::l::::（:::::l,-&apos;&apos;&quot;ヽ､::::::::::::::l::::::::,-‐ｰ-､::::::,-‐ｰ､;;;;;;;;ﾐ&apos;,:::::ヽ:三≡l;;;;;;;;::::::::::::::::::::::::::::::::::::::::::::::::l
        ///    l:::::::l:/l&quot;ヽ:＼.__　 ｀`‐-､::l::::/　　　　 ｀&apos;　　　　　　　:l::::::l::::::::::::l;;;;;:;:;:;:::::::::::::::::::::::::::::::::::::::::::::l
        ///    !:::::::l　l　 ｀‐､三三二=-ヽl::l　　　　　　　　　　　　　　l::ﾉ:::::::::,-､;;;;;:;:;:;:;::::::::::: [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ∧＿∧
        ///　 （　・∀・） 　ｽｶｯ
        ///　と　　　　）
        ///　　 Ｙ　/ノ　　|　|　＼＼
        ///　　　 /　）　 /　/
        ///　 ＿/し&apos;　／／／￣~~~ ヽﾏﾄﾘｸｰｽ
        ///　（＿フ彡　　　|　| し( 、 Ａ ,）つ
        ///　　　　　　　 （＿ﾉ_.ﾉ　Ｖ￣Ｖ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
    }
}
