'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.239
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("cfw_trans_inst.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  インストールが完了しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property s5() As String
            Get
                Return ResourceManager.GetString("s5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  install completed!! に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property s5_e() As String
            Get
                Return ResourceManager.GetString("s5_e", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  USB接続してないかメモリースティックフォーマット時自動生成されるPSPフォルダとMEMSTICK.INDが見つかりませんでした に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property s6() As String
            Get
                Return ResourceManager.GetString("s6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  cannot find PSP directory and hidden file &quot;MEMSTICK.IND&quot; created  with psp-xmb memorystick format menu に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property s6_e() As String
            Get
                Return ResourceManager.GetString("s6_e", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  隠しファイルMEMSTICK.INDがない場合はメモリースティックのルートに作成してください に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property s7() As String
            Get
                Return ResourceManager.GetString("s7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  if there are no MEMSTICK.IND,please make it on memorysitck root directory  に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property s7_e() As String
            Get
                Return ResourceManager.GetString("s7_e", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
