//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.269
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace binary32_normalize.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("binary32_normalize.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   符号: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string s1 {
            get {
                return ResourceManager.GetString("s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sign: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string s1_e {
            get {
                return ResourceManager.GetString("s1_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指数: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string s2 {
            get {
                return ResourceManager.GetString("s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   exponent: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string s2_e {
            get {
                return ResourceManager.GetString("s2_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   仮数: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string s3 {
            get {
                return ResourceManager.GetString("s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   fraction: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string s3_e {
            get {
                return ResourceManager.GetString("s3_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指数が上限かつ仮数が０の場合、無限大となります. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string s4 {
            get {
                return ResourceManager.GetString("s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if exponet is filled  and fraction is  0, infinty number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string s4_e {
            get {
                return ResourceManager.GetString("s4_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指数が上限かつ仮数が0出ない場合、無限大を超えてるため非数になります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string s5 {
            get {
                return ResourceManager.GetString("s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   if exponet is filled  and fraction is not 0, not a number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string s5_e {
            get {
                return ResourceManager.GetString("s5_e", resourceCulture);
            }
        }
    }
}
